name: Repo SemVer
description: Find the greatest semantic version Git tag and return it, along with ("major", "minor", "patch", etc.) increments.
author: Marten Lohstroh <marten@berkeley.edu>
inputs:
  path:
    type: string
    description: Path to the repository
    default: ${{ github.workspace }}
  repo:
    type: string
    description: Name of repository to check out
    required: false
  bump:
    type: string
    description: Requested version increment in bump output
    required: false
  override:
    type: string
    description: Manually specified current version
    required: false
  planned:
    type: string
    description: Version to compare against current
    required: false
  prerelease:
    type: string
    description: String to be used in the next-prerelease output
    required: false
  build:
    type: string
    description: String to be used in next-build output
    required: false

outputs:
  tag:
    description: Tag corresponding to current version
    value: ${{ steps.find.outputs.tag }}    
  current:
    description: Current version
    value: ${{ steps.cur.outputs.ver }}
  bump:
    description: Requested version bump
    value: ${{ steps.bump.outputs.ver }}
  prefix:
    description: Prefix used in the tag
    value: ${{ steps.prefix.output.str }}
  next-prerelease:
    description: Prerelease increment (over current semver tag)
    value: ${{ steps.incr.outputs.prerelease }}  
  next-patch:
    description: Patch increment (over current semver tag)
    value: ${{ steps.incr.outputs.patch }}
  next-minor:
    description: Minor increment (over current semver tag)
    value: ${{ steps.incr.outputs.minor }}
  next-major:
    description: Major increment (over current semver tag)
    value: ${{ steps.incr.outputs.major }}
  next-release:
    description: Release increment (over current semver tag)
    value: ${{ steps.incr.outputs.release }}
  next-build:
    description: Release increment (over current semver tag)
    value: ${{ steps.build.outputs.incr }}  
  planned-is-valid:
    description: True if planned input is valid semver greater than current
    value: ${{ steps.test.outputs.greater }}

branding:
  icon: tag
  color: green
runs:
  using: composite
  steps:
    - name: Check out repository if one is specified
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        path: ${{ inputs.path }}
      if: ${{ inputs.repo != '' }}
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash
    - name: Install greatest-semver-tag
      run: |
        wget -O /usr/local/bin/greatest-semver-tag https://raw.githubusercontent.com/lhstrh/greatest-semver-tag/main/greatest-semver-tag.sh
        chmod +x /usr/local/bin/greatest-semver-tag
      shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: Find the greatest semver tag
      id: find
      working-directory: ${{ inputs.path }}
      run: |
        echo "tag=$(greatest-semver-tag)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set current version based on stripped tag
      id: cur
      run: >
        if [[ "${{ inputs.override }}" != "" ]]; then
          if [[ $(semver compare ${{ inputs.override }} 0.0.0) != "1" ]]; then
            if [[ "${{ inputs.override }}" != "0.0.0" ]]; then
              echo "Invalid override."; exit 1
            fi
          fi
          echo "ver=${{ inputs.override }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ steps.find.outputs.tag }}" = "" ]]; then
          echo "ver=0.0.0" >> "$GITHUB_OUTPUT"
        else
          echo "ver=$(echo "${{ steps.find.outputs.tag }}" | sed 's/^[^0-9]*//')" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Determine the prefix and set it
      id: prefix
      run: >
        ver="${{ steps.cur.outputs.ver }}";
        if [[ "${{ inputs.override }}" != "" ]]; then
          echo "str=$(echo ${${{ inputs.override }}%"$ver"})" >> "$GITHUB_OUTPUT"
        elif [[ "${{ steps.find.outputs.tag }}" != "" ]]; then
          echo "str=$(echo ${${{ steps.find.outputs.tag }}%"$ver"})" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Test if planned input is greater than current
      id: test
      run: >
        if [[ $(semver compare ${{ inputs.planned }} ${{ steps.cur.outputs.ver }}) -eq 1 ]]; then
          echo "greater=true" >> "$GITHUB_OUTPUT"
        else
          echo "greater=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
      if: ${{ inputs.planned != '' }}
    - name: Produce increments
      id: incr
      run: |
        echo "patch=$(semver bump patch ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
        echo "minor=$(semver bump minor ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
        echo "major=$(semver bump major ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
        echo "prerelease=$(semver bump prerel ${{ inputs.prerelease }} ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
        echo "release=$(semver bump release ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Produce build increment if a build string was given
      id: build
      run: |
        echo "incr=$(semver bump build ${{ inputs.build }} ${{ steps.cur.outputs.ver }})" >> "$GITHUB_OUTPUT"
      shell: bash    
      if: ${{ inputs.build != '' }}
    - name: Produce version bump (if requested)
      id: bump
      run: >
        if [[ "${{ inputs.bump }}" = "patch" ]]; then
          echo "ver=${{ steps.incr.outputs.patch }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.bump }}" = "minor" ]]; then
          echo "ver=${{ steps.incr.outputs.minor }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.bump }}" = "major" ]]; then
          echo "ver=${{ steps.incr.outputs.major }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.bump }}" = "release" ]]; then
          echo "ver=${{ steps.incr.outputs.release }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.bump }}" = "prerelease" ]]; then
          echo "ver=${{ steps.incr.outputs.prerelease }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ inputs.bump }}" = "build" ]]; then
          if [[ "${{ inputs.build }}" != "" ]]; then
            echo "ver=${{ steps.incr.outputs.next-build }}" >> "$GITHUB_OUTPUT"
          else
            echo "The build input must be set when requesting build bump";  
          fi
        else
          echo "::error::Invalid version bump: ${{ inputs.bump }} (options: major|minor|patch|release|prerelease|build)";
          exit 1
        fi
      if: ${{ inputs.bump != '' }}
      shell: bash
    - name: Print results
      run: |
        echo "Greatest tag: ${{ steps.find.outputs.tag }}"
        echo "Used prefix: ${{ steps.prefix.outputs.str }}"
        echo "Current version: ${{ steps.cur.outputs.ver }}"
        echo "Version bump (if requested): ${{ steps.bump.outputs.ver }}"
        echo "Prerelease increment: ${{ steps.incr.outputs.prerelease }}"
        echo "Patch increment: ${{ steps.incr.outputs.patch }}"
        echo "Minor increment: ${{ steps.incr.outputs.minor }}"
        echo "Major increment: ${{ steps.incr.outputs.major }}"
        echo "Release increment: ${{ steps.incr.outputs.release }}"
        echo "Build increment (if specified): ${{ steps.build.outputs.incr }}"
      shell: bash
